[package]
name = "concurrency-future-example"
version = "0.1.0"
edition = "2021"

[dependencies]
blake3 = "1.5.3"
tokio = { version = "1", features = ["full"] }
anyhow = "1"
futures = "0.3"
tokio-utils = "0.1"
rayon = "1"