[package]
name = "concurrency-future"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = "1.0.204"
serde_yaml = "0.9.34"
tokio = { version = "1", features = ["full"]}
toml = "0.8.16"
